name: Build Linux
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Current date time
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        id: time
        with:
          format: "YYYYMMDDHHmmss"

      - uses: actions/checkout@v4
      - name: setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install build-essential make cmake
          sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          sudo gunzip /usr/local/bin/ninja.gz
          sudo chmod a+x /usr/local/bin/ninja

      - name: checkout llvm
        run: git clone --single-branch --depth 1 --branch main https://github.com/llvm/llvm-project $GITHUB_WORKSPACE/llvm-project

      - name: setup build
        run: |
          mkdir -p $GITHUB_WORKSPACE/llvm-project/build \
            && cd $GITHUB_WORKSPACE/llvm-project/build \
            && git checkout main \
            && cmake -G "Ninja" -S ../llvm \
              -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/llvm-main" \
              -DCMAKE_BUILD_TYPE="Release" \
              -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
              -DLLVM_ENABLE_ASSERTIONS=ON \
              -DLLVM_ENABLE_PROJECTS="clang;lld" \
              -DLLVM_INCLUDE_TESTS=Off \
              -DLLVM_INCLUDE_EXAMPLES=Off \
              -DLLVM_OPTIMIZED_TABLEGEN=On \
            && ninja -C . install

      - name: package results
        run: |
          pushd $GITHUB_WORKSPACE/llvm-main \
            && tar -cJf $GITHUB_WORKSPACE/clang+llvm-main-x86_64-linux.tar.xz \
               . \
            && ls $GITHUB_WORKSPACE \
            && popd

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: latest
          name: LLVM main ${{ steps.time.outputs.time }}
          makeLatest: false
          artifacts: clang+llvm-main-x86_64-linux.tar.xz
